config/routes.rb
# coding: utf-8
AuricaCurkan::Application.routes.draw do

  devise_for :users do
    get "sign_in", :to => "devise/sessions#new"


    #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

    resources :contacts
    resources :events
    root :to => 'main#index'
    match '/logout' => 'sessions#destroy', :as => :logout
    match '/login' => 'sessions#new', :as => :login
    match '/register' => 'users#create', :as => :register
    match '/signup' => 'users#new', :as => :signup
    #resources :users
    resource :session
    match '/foto' => 'fotos#index', :as => :foto_index
    match '/video' => 'videos#index', :as => :video_index
    match '/about' => 'main#about', :as => :about_index
    match '/schedule' => 'main#schedule', :as => :schedule
    match '/payment' => 'main#payment', :as => :payment
    match '/camp_scheld' => 'main#camp_scheld', :as => :camp_scheld
    match '/help' => 'main#help', :as => :help
    match '/dance' => 'main#about_dance', :as => :about_dance_index
    resources :videos
    resources :publications
    resources :foto_albums
    resources :collectives
    resources :fotos do
      collection do
        post :swfupload
      end


    end

    resources :foto_albums
    resources :news
  end
  match '/:controller(/:action(/:id))'
end

app/views/shared/_footer.html.erb
<p>© 2010-2011 Аурика Цуркан, г. Пенза. При поддержке <%= link_to "Denzhakov.ru", "http://denzhakov.ru/" %></p>
<% if  Rails.env.production?  %>
    <div class="counters">

<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t21.4;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";h"+escape(document.title.substring(0,80))+";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров за 24"+
" часа, посетителей за 24 часа и за сегодня' "+
"border='0' width='88' height='31'><\/a>")
//--></script><!--/LiveInternet-->

 <!--Openstat--><span id="openstat2083858"></span><script type="text/javascript">
var openstat = { counter: 2083858, image: 5012, next: openstat, track_links: "all" }; document.write(unescape("%3Cscript%20src=%22http" +
(("https:" == document.location.protocol) ? "s" : "") +
"://openstat.net/cnt.js%22%20defer=%22defer%22%3E%3C/script%3E"));
</script><!--/Openstat-->

<!-- Yandex.Metrika -->
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<div style="display:none;"><script type="text/javascript">
try { var yaCounter862275 = new Ya.Metrika(862275); } catch(e){}
</script></div>
<noscript><div style="position:absolute"><img src="//mc.yandex.ru/watch/862275"  alt="" /></div></noscript>
<!-- /Yandex.Metrika -->
  
<!--google-analytics-->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-15305242-1");
pageTracker._trackPageview();
} catch(err) {}</script>
  <!--/google-analytics-->
</div>
<% end %>

app/views/shared/_menu.html.erb
 <div class="menu">
    <div class="menu_list">
      <ul>
        <li>|</li>
        <li><%= link_to_unless_current "Главная", root_path %></li>
        <!--<li>|</li>-->
        <!--<li ><%#= link_to_unless_current "Расписание выступлений", camp_scheld_path, :style=>"color:red;" %></li>-->
        <!--<li>|</li>-->
        <!--<li><%#= link_to_unless_current "Оплата за участие", payment_path %></li>-->
        <!--<li>|</li>-->
        <!--<li><%#= link_to_unless_current "Проживание для иногородних", help_path %></li>-->
        <li>|</li>
        <li><%= link_to_unless_current "Новости", events_path %></li>
        <li>|</li>
        <li><%= link_to_unless_current "Статьи", publications_path %></li>
        <li>|</li>
        <li><%= link_to_unless_current "Видео", videos_path %></li>
        <li>|</li>
        <li><%= link_to_unless_current "Фотоальбомы", foto_albums_path %></li>
        <li>|</li>
        <li><%= link_to_unless_current "Расписание занятий", schedule_path %></li>
        <li>|</li>
        <li><%= link_to_unless_current "Заявка на выступление", new_contact_path %></li>
        <li>|</li>
        <li><%= link_to_unless_current "Обо мне", about_index_path %></li>

        <li>|</li>
        <!--<li><%#= link_to_unless_current "Виды танца", about_dance_index_path %></li>-->
        <!--<li>|</li>-->
            <%= render :partial => 'users/user_bar' %>
        <li>|</li>
      </ul>
    </div>
  </div>